### PR TITLE
29 interaction handler rework

### LINKED ISSUE #29: Remove verifier command from command handler check
## Description
With the current implementation, every command is routed to be checked by the event CommandHandler. This unfortunately means that if the bot crashes, persistent commands such as the verifier command will need to be re-enabled manually. In the case of the verifier command, and exec has to come in to manually call the `/verifier` in the designated channel again.

## Steps To Reproduce
1.
2. 
3. 

## Approach

---

### PR DESCRIPTION
**Pull request by alexanderfzz**
Closes #29

### CODE REVIEW

**Review by asmahood — CHANGES_REQUESTED** [review]
Sorry, there was probably a miscommunication on my part but this is not what I meant.

The overarching theme of my requested changes is SRP (Single Responsibility Principle). Things need to be responsible for doing one thing and one thing only.

- there needs to be two event handlers: one for handling application commands, one for handling button interactions.
  - the application command handler was already called CommandHandler, you don't need to change this
  - we need a new event handler that just handles button interactions and determines what function to run based on what button was pressed
  - this means that if we add a new buttons in the future, this event handler will also be responsible for running the correct code in that new buttons case
- the verify command should ONLY be responsible for displaying the message and the buttons, anything that isn't that needs to be moved somewhere else
  - due to the above points, the other code that isn't responsible for displaying the message/buttons SHOULDN'T go into the new ButtonInteraction handler, since that would be giving it a second responsibility. It will have to live in a new place. That place is up to you

If you have any questions feel free to message me.

File: src/commands/Admin/Verifier.ts [hunk 1]
```diff
@@ -407,4 +346,56 @@ export default class Verifier extends Command {
...
+        }
+
+        // verification limit check
+        let remainingAttempts: number = (await VerificationAttempts.findAll({
+            where: {
+                discord_client_id: buttonInteraction.user.id,
+            },
+        }))[0]?.dataValues.remaining_failed_attempts;
+        remainingAttempts = remainingAttempts == undefined ? defaultFailedAttemptLimit : remainingAttempts;
+
```
Comment (asmahood) [inline src/commands/Admin/Verifier.ts:366]: This entire function should be moved out of this command and into its own module, like `handlers` or something similar

File: src/events/InteractionHandler.ts
Comment (asmahood) [inline src/events/InteractionHandler.ts:1]: Revert this file to its original state, and move the logic specific to handling button interaction into its own event handler (`events/ButtonInteractionHandler.ts`)

File: src/events/InteractionHandler.ts [hunk 2]
```diff
@@ -64,4 +71,17 @@ export default class CommandHandler extends Event {
...
+    private handleButtonInteractions(interaction: ButtonInteraction): void {
+        // This function only manages peristent buttons
+        // As of the current design, this only includes the buttons from the Verifier command
+        if (interaction.customId != `Verifier|verifyEmailButton` && interaction.customId != `Verifier|verifyCodeButton`) {
+            return;
+        }
+
+        const command: Verifier = this.client.commands.get("verifier") as Verifier;
+        command.handleButtonInteractions(interaction);
+    }
```
Comment (asmahood) [inline src/events/InteractionHandler.ts:86]: Then instead of initializing a command (which doesn't make sense in this context), call the new "handler" function you define from the command code

**Review by asmahood — APPROVED** [review]
